/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * Swagger Petstore
 * This is a sample Petstore server.  You can find 
out more about Swagger at 
[http://swagger.io](http://swagger.io) or on 
[irc.freenode.net, #swagger](http://swagger.io/irc/).

 * OpenAPI spec version: 1.0.0
 */

/**
 * pet status in the store
 */
export type PetStatus = 'available' | 'pending' | 'sold';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetStatus = {
  available: 'available' as PetStatus,
  pending: 'pending' as PetStatus,
  sold: 'sold' as PetStatus,
};
